"""
Replay Buffer
=============
Stores training examples generated by self-play and provides random
mini-batch sampling for the network training step.

Why a replay buffer?
--------------------
In AlphaZero, each training example is a tuple:
  (encoded_state, mcts_policy, value_target)

generated during self-play. We don't train on these immediately — instead
we accumulate them in a buffer and sample randomly. This breaks temporal
correlations (nearby game states are very similar and would cause the
network to overfit a single game's outcome) and reuses each example
across multiple training epochs.

Circular buffer
---------------
Once the buffer reaches capacity, new examples overwrite the oldest ones.
This keeps the data fresh — older games from a weaker model version are
gradually pushed out as the agent improves.

Pre-allocated mode
------------------
When state_shape and policy_size are provided at construction, the buffer
stores all data in three contiguous numpy arrays of shape:
  states   (capacity, *state_shape)   float32
  policies (capacity, policy_size)    float32
  values   (capacity,)                float32

Sampling then reduces to a single numpy fancy-index slice per array rather
than a Python list comprehension + torch.stack, which is measurably faster
once the buffer grows large.  The trainer always constructs with these
dimensions known, so this is the default code path.

Capacity guidance
-----------------
  DEBUG  :   500 examples  (~a few games)
  DEV    : 50 000 examples  (~1 000 games)
  FULL   : 500 000 examples (~10 000 games)

Storage
-------
The buffer stores tensors on CPU regardless of where training happens.
Batches are moved to the training device inside the trainer loop.
"""

from __future__ import annotations

import random
import numpy as np
import torch


class ReplayBuffer:
    """
    Fixed-capacity circular buffer of (state, policy, value) training examples.

    Parameters
    ----------
    capacity    : Maximum number of examples to hold. Oldest are dropped when full.
    state_shape : Shape of a single encoded state, e.g. (19, 8, 8).
                  When provided together with policy_size, activates the fast
                  pre-allocated numpy storage mode.
    policy_size : Length of the policy vector, e.g. 170 for standard checkers.
    """

    def __init__(
        self,
        capacity: int,
        state_shape: tuple[int, ...] | None = None,
        policy_size: int | None = None,
    ):
        self.capacity      = capacity
        self._state_shape  = state_shape
        self._policy_size  = policy_size
        self._pos: int     = 0   # write pointer (wraps at capacity)
        self._len: int     = 0   # number of valid entries

        self._preallocated = state_shape is not None and policy_size is not None

        if self._preallocated:
            self._states   = np.empty((capacity, *state_shape),  dtype=np.float32)
            self._policies = np.empty((capacity, policy_size),   dtype=np.float32)
            self._values   = np.empty(capacity,                  dtype=np.float32)
        else:
            # Legacy list mode — used when shape info is not available
            self._states:   list[torch.Tensor] = []
            self._policies: list[np.ndarray]   = []
            self._values:   list[float]         = []

    # ── Write ─────────────────────────────────────────────────────────────────

    def add(self, state: torch.Tensor, policy: np.ndarray, value: float) -> None:
        """
        Insert one training example.

        Parameters
        ----------
        state  : Encoded board tensor of shape (num_channels, 8, 8), on CPU.
        policy : MCTS visit-count probabilities, shape (action_size,).
        value  : Game outcome from the current player's perspective (+1/0/-1).
        """
        if self._preallocated:
            self._states[self._pos]   = state.numpy()
            self._policies[self._pos] = policy
            self._values[self._pos]   = value
            if self._len < self.capacity:
                self._len += 1
        else:
            if len(self._states) < self.capacity:
                self._states.append(state)
                self._policies.append(policy)
                self._values.append(value)
            else:
                self._states[self._pos]   = state
                self._policies[self._pos] = policy
                self._values[self._pos]   = value

        self._pos = (self._pos + 1) % self.capacity

    def add_many(self, examples: list[tuple[torch.Tensor, np.ndarray, float]]) -> None:
        """Bulk-insert a list of (state, policy, value) tuples."""
        for state, policy, value in examples:
            self.add(state, policy, value)

    # ── Read ──────────────────────────────────────────────────────────────────

    def sample(self, batch_size: int) -> tuple[torch.Tensor, torch.Tensor, torch.Tensor]:
        """
        Draw a random mini-batch.

        Returns
        -------
        states   : (batch_size, num_channels, 8, 8) float32 tensor.
        policies : (batch_size, action_size)         float32 tensor.
        values   : (batch_size, 1)                   float32 tensor.
        """
        n = len(self)
        if self._preallocated:
            indices  = np.random.choice(n, batch_size, replace=False)
            # Fancy-index into contiguous arrays; .copy() ensures torch gets
            # writable memory (required for non-contiguous fancy-index results)
            states   = torch.from_numpy(self._states[indices].copy())
            policies = torch.from_numpy(self._policies[indices].copy())
            values   = torch.from_numpy(self._values[indices, np.newaxis].copy())
            return states, policies, values

        indices  = random.sample(range(n), batch_size)
        states   = torch.stack([self._states[i] for i in indices])
        policies = torch.tensor(
            np.stack([self._policies[i] for i in indices]), dtype=torch.float32
        )
        values = torch.tensor(
            [[self._values[i]] for i in indices], dtype=torch.float32
        )
        return states, policies, values

    # ── Persistence ───────────────────────────────────────────────────────────

    def state_dict(self) -> dict:
        """
        Serialise buffer contents for checkpointing.

        Always emits data as a list of arrays (regardless of storage mode) so
        the format is compatible with both pre-allocated and legacy buffers.
        """
        n = len(self)
        if self._preallocated:
            # Reconstruct chronological order (oldest first) for clean save
            if n < self.capacity:
                states_out   = list(self._states[:n])
                policies_out = list(self._policies[:n])
                values_out   = list(self._values[:n])
            else:
                # Oldest entry sits at self._pos; wrap around to get order
                idx          = list(range(self._pos, self.capacity)) + list(range(self._pos))
                states_out   = list(self._states[idx])
                policies_out = list(self._policies[idx])
                values_out   = list(self._values[idx])
            return {
                "capacity":    self.capacity,
                "pos":         self._pos,
                "state_shape": self._state_shape,
                "policy_size": self._policy_size,
                "states":      states_out,
                "policies":    policies_out,
                "values":      values_out,
            }

        return {
            "capacity": self.capacity,
            "pos":      self._pos,
            "states":   [s.numpy() for s in self._states],
            "policies": list(self._policies),
            "values":   list(self._values),
        }

    @classmethod
    def from_state_dict(cls, d: dict) -> "ReplayBuffer":
        """Restore a buffer from a checkpoint dict."""
        state_shape = d.get("state_shape")
        policy_size = d.get("policy_size")
        buf = cls(d["capacity"], state_shape=state_shape, policy_size=policy_size)

        states_list   = d["states"]
        policies_list = d["policies"]
        values_list   = d["values"]
        n = len(states_list)

        if buf._preallocated:
            for i in range(n):
                buf._states[i]   = np.asarray(states_list[i],   dtype=np.float32)
                buf._policies[i] = np.asarray(policies_list[i], dtype=np.float32)
                buf._values[i]   = float(values_list[i])
            buf._len = n
            # Saved data is in chronological order; write pointer wraps naturally
            buf._pos = n % buf.capacity
        else:
            buf._pos      = d["pos"]
            buf._states   = [torch.from_numpy(np.asarray(s, dtype=np.float32)) for s in states_list]
            buf._policies = [np.asarray(p, dtype=np.float32) for p in policies_list]
            buf._values   = [float(v) for v in values_list]

        return buf

    # ── Dunder ────────────────────────────────────────────────────────────────

    def __len__(self) -> int:
        return self._len if self._preallocated else len(self._states)

    def __repr__(self) -> str:
        return f"ReplayBuffer({len(self)}/{self.capacity})"
